### ISSUE TITLE
Update dependencies (latest clojurescript, cljsbuild, etc)

### ISSUE THREAD

**Issue by lbradstreet** [lbradstreet/instaparse-cljs#6]
Currently seeing some test failures.

```
FAIL in (instaparse.grammars/testing-grammars) (:)
expected: (= (parses grammar59 :S "aaabbbccc") (quote ([:S "a" "a" "a" "b" "b" "b" "c" "c" "c"])))
  actual: (not (= () ([:S "a" "a" "a" "b" "b" "b" "c" "c" "c"])))

Testing instaparse.abnf-test

Testing instaparse.repeat-test

Testing instaparse.core-test

ERROR in (instaparse.core-test/parsing-tutorial) (:)
expected: (= ((insta/parser "S = 'a' / eps") "a") [:S "a"])
  actual:
Error: No matching clause:
    at Error (native)
    at Yy (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:10234:15)
    at eval (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:3449:33)
    at eval (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:3450:8)
    at Hg (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:2404:51)
    at Gg.a.M (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:2439:3)
    at Cc (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:860:14)
    at Pg (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:2592:18)
    at Function.u.b (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:2788:13)
    at Oi (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:3571:12)

ERROR in (instaparse.core-test/parsing-tutorial) (:)
expected: (= ((insta/parser "S = 'a' / eps") "") [:S])
  actual:
Error: No matching clause:
    at Error (native)
    at Yy (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:10234:15)
    at eval (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:3449:33)
    at eval (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:3450:8)
    at Hg (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:2404:51)
    at Gg.a.M (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:2439:3)
    at Cc (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:860:14)
    at Pg (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:2592:18)
    at Function.u.b (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:2788:13)
    at Oi (eval at <anonymous> (/private/var/folders/7f/z4x1xdtd77dg4v8qbb080n_h0000gn/T/node-runner2270611657897868901.js:1:0), <anonymous>:3571:12)
```

**Comment by lbradstreet** [comment]
Done
